### ISSUE TITLE
API Query request (Schools)

### ISSUE THREAD

**Issue by ayanez17** [unicef/magicbox-open-api#15]
[sampleapi.pdf](https://github.com/unicef/magicbox-open-api/files/1225874/sampleapi.pdf)

Sample API Call:
getSchools($params[ ] ) // return list of schools in GEOJSON (<—click for more information) format that
satisfy those params
addSchools($params[ ] ) // insert school to UNICEF database
$Params $params are in key value pairs i.e. school_name => ‘school1’
$params include: ‘country_code’, ‘county’, ‘state’, ‘country region’,’electricity’, ‘type_of_connection’, ‘type_school’, ‘max_entries’ ( LIMIT to max_entries) ...etc
 What to return:
The output should be a GEOJSON object of type Point with the appropriate coordinates.
The GEOJSON object should have all parameters (img 1) as a property in the the GEOJSON properties entry.
Sample Return :
getSchools([‘country_code’,’type_school’,’max_entries’],[‘BR’,’private’,2])
{ "type": "FeatureCollection", "features": [
{
"type": "Feature", "geometry": {
"type": "Point", "coordinates": [
-77.12911152370515,
38.79930767201779 ]
}, "properties": {
"name": "School_Name_1", "country_code": "BR",
“type_school”: “private”, .
.
. “prop_n”: “prop_n
} },
{
"type": "Feature", "geometry": {
"type": "Point", "coordinates": [
-87.12911152370515,
38.79930767201779 ]
}, "properties": {
"name": "School_Name_2", "country_code": "BR",
“type_school”: “private”, .
.
. “prop_n”: “prop_n”
}
} ]
getSchools($params[ ]):
    }

**Comment by mikefab** [comment]
This API will mainly just field queries. So this probably isn't the place to request: addSchools($params[ ] ) // insert school to UNICEF database

For adding, updating, and deleting schools, we'd need to add an API to ActiveAdmin athttps://github.com/unicef/project-connect/. Please add an issue for this there.

@ayanez17 @mfajardorua
