### ISSUE TITLE
CHECKS FOR EACH REGISTER

### ISSUE THREAD

**Issue by mfajardorua** [unicef/magicbox-open-api#17]
CHECKS FOR EACH REGISTER

Check Coordinates within the country or the admin boundary

LatLong outside shapefile – Not valid, send message
Assign Admin ID
Check Mandatory fields are included (country, name, latlong)

No name- **Valid** but send message
No LatLong – Valid but with coordinate field =NULL

Check format of the fields are according to expected (number, string etc.)
Check if Duplicates in the file (same lat&long or +-Delta ) – TBD; for now all valid

**Comment by mikefab** [comment]
This repo was created to do this job: https://github.com/unicef/validate_geo_coordinates. It won't send an email, but we'll add endpoints that return the schools that do not have valid coordinates.
