### ISSUE TITLE
Add endpoint: Return array of countries with school data

### ISSUE THREAD

**Issue by mikefab** [unicef/magicbox-open-api#25]
Branch off "schools" to add endpint /api/v1/schools/countries

Should return array of country code, ie: ['bra', 'col', 'mex'...]

**Comment by mikefab** [comment]
Still need to provide screenshot and proof of test.

**Comment by ayanez17** [comment]
Screenshot:
<img width="1097" alt="screen shot 2018-01-22 at 10 34 45 am" src="https://user-images.githubusercontent.com/18299052/35228918-f160ea48-ff5f-11e7-83f0-fac68ffa8fe7.png">

**Comment by thoat** [comment]
@mikefab do you want to close this issue yet?

**Comment by mikefab** [comment]
Why yes, yes I would! Thank you, @thoat!
