### ISSUE TITLE
Put School under Schools in swagger

### ISSUE THREAD

**Issue by mikefab** [unicef/magicbox-open-api#28]
![screen shot 2018-01-10 at 9 31 51 pm](https://user-images.githubusercontent.com/42814/34805767-c2e407ba-f64d-11e7-90a3-a46226886f7d.png)

The school endpoint should be within the schools node.

**Comment by mikefab** [comment]
Hi Fredy, is this done? If so, could you provide a screenshot?

**Comment by ayanez17** [comment]
Done.
<img width="1258" alt="screen shot 2018-01-22 at 10 30 48 am" src="https://user-images.githubusercontent.com/18299052/35228788-9506ac92-ff5f-11e7-920d-e8ccaaaec1cd.png">
