### ISSUE TITLE
Archive this repository if it is no longer used

### ISSUE THREAD

**Issue by jwflory** [unicef/magicbox-open-api#55]
Consider marking this repo as archived in the [settings menu](https://github.com/unicef/magicbox-open-api/settings) if active development is no longer happening. See the screenshot below for how to do this:

![Danger Zone - Archive this repository](https://user-images.githubusercontent.com/4721034/49455806-ca4d3980-f7b5-11e8-9d3a-69e01f6ea0ea.png "Danger Zone - Archive this repository")

This does two things:

1. Clearly communicates to non-UNICEF staff that active development is no longer happening here
2. Stops sending known security vulnerability emails about this repo every week

**Comment by mikefab** [comment]
An instance of this repo still serves the global school mapping and mobility sites.
